apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-cloudwatch-metrics.fullname" . }}
  labels:
    {{- include "aws-cloudwatch-metrics.labels" . | nindent 4 }}
data:
  cwagentconfig.json: |
    {
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "{{ .Values.clusterName }}",
            "metrics_collection_interval": 60
          }
        },
        "force_flush_interval": 5
      }
    },
      "metrics": {
        "append_dimensions": {
          "InstanceId": "${aws:InstanceId}"
        },
        "metrics_collected": {
          "ethtool": {
            "interface_include": [
              "*"
            ],
            "metrics_include": [
              "rx_packets",
              "tx_packets",
              "bw_in_allowance_exceeded",
              "bw_out_allowance_exceeded",
              "conntrack_allowance_exceeded",
              "linklocal_allowance_exceeded",
              "pps_allowance_exceeded"
            ]
          }
        }
      }
    
